### PR TITLE
fix: freshen files was failing with exception, put in a fix for it

### PR DESCRIPTION
**Pull request by puneetloya**
Added the Metadata directive, this copies the whole object and updates the last modified timestamp of the file

### CODE REVIEW

**Comment by cin** [comment]
will this help with https://github.com/instaclustr/cassandra-backup/issues/2 as well?

**Comment by puneetloya** [comment]
I hope it does. I can submit an MR, there too. But not satisfied by the fact that it copies the whole object again along with the metadata. Not sure if there is a way to only copy over the metadata

**Comment by cin** [comment]
I think the only way you can update the metadata (at least in S3) is to make a copy of the object and set the metadata. :( https://stackoverflow.com/questions/32646646/how-do-i-update-metadata-for-an-existing-amazon-s3-file

**Comment by cin** [comment]
i'll try to test these changes tomorrow. BTW, thanks for the submission!

**Comment by cin** [comment]
I just tested and it actually does resolve https://github.com/instaclustr/cassandra-backup/issues/2 as well. The copy seems occur pretty quickly though I'm sure it'll incur some cost.

**Pull request merged**
